n,xp = input().split()
xpiYoda,xpiLuke,xpiAhsoka = input().split()
n = int(n)
xp = int(xp)
xpiYoda = int(xpiYoda)
xpiLuke = int(xpiLuke)
xpiAhsoka = int(xpiAhsoka)
novoxp1 = int(xpiYoda + n*xp)
novoxp2 = int(xpiLuke + n*xp)
novoxp3 = int(xpiAhsoka + n*xp)

print("yoda","",novoxp1)
print("Luke","",novoxp2)
print("Ahsoka","",novoxp3)